### PR TITLE
This PR suggests to use yarn instead of npm as CRA itself prefers yarn over npm.

### PR DESCRIPTION
**Pull request by sahilrajput03**
CRA uses yarn to install dependencies when using `npx create-react-app my-app` if yarn is already installed on the system. 
Also if we forcefully use npm, with command `npx create-react-app --use-npm`, the project size expands to `336mb` with nothing touched.

Where as if CRA uses yarn(if its already installed on system), via command `npx create-react-app my-app`, the project size expands to `264mb` with nothing touched.

**Also, the new `package.json` in this repo will tell yarn to make use of workspace technique to manage dependencies of all the projects we create either with `yarn create react-app my-app` or any project cloned from github(or elsewhere) in a very smart way, that no single dependency would be installed twice for any project in any nested folder of our project.**

**This will same memory in a very efficient manner and maintaining distinct version of dependencies across different node projects as well, during the course, and is also the way to manage any large otherwise production project.**

Another benefit of using yarn workspaces is that with a single `yarn` command in the root will install dependencies if you ever earlier chose to delete node_modules from the root or anywhere in the nested node projects.

Yarn is sensible.

Thanks.

### CODE REVIEW

**Comment by sahilrajput03** [comment]
Somebody wants to try how this setup works, simply go [here](https://github.com/sahilrajput03/example-submission-repository/tree/patch-1) and follow `Readme.md` there.

**Comment by sahilrajput03** [comment]
**Somebody wants to try how this setup works, simply go [clone this repo and use `git checkout patch-1`](https://github.com/sahilrajput03/example-submission-repository/tree/patch-1) and read Readme.md there for more info.**

### Testing with workspace...

```bash
git clone https://github.com/sahilrajput03/example-submission-repository/tree/master example-repo
cd example-repo
git checkout patch-1

cd part0 && mkdir proj-1 && cd proj-1 && yarn init -y && yarn add express cors dotenv
cd ..
git clone https://github.com/fullstack-hy2020/part3-notes-backend backend && cd backend && yarn
cd ..
yarn create react-app my-react-app
cd .. # Back to root of fso-workspace
# Testing size of node_modules...
du -sh node_modules
#Output:: 273M	node_modules
du -sh part0/proj-1/node_modules
# Output: no-output as "'node_modules' folder doesn't exist, as all dependencies are installed in root node_modules folder"
du -sh part0/backend/node_modules
#Output:: 8.0K	part0/backend/node_modules
du -sh part0/my-react-app/node_modules
#Output:: 8.0K	part0/my-react-app/node_modules
```
So, above results ensures the rightful setup of yarn workspaces!!

**Comment by Kaltsoon** [comment]
You could simply remove node_modules directories that you don't need. This seems quite a hassle and would most likely cause confusion and issues. Also, it doesn't make sense to switch to yarn just for this reason. Npm is used all over the material and is still the de facto package manager.

**Comment by sahilrajput03** [comment]
Despite npm being defacto solution for npm, yarn still remains a choice for anybody to choose.

Yarn is more efficient, robust, fast, and preffered choice among technologists these days.

Technology should get better, and thereby testing, module-resolution, dependency re-usage mechanisms.

Won't it be good if dependencies just don't get re-installed/re-downloaded again if ever earlier installed/dowloaded for that specific version of a npm package what we require again in a new project, atleast on our local machine.

I just want to say, the developer experience should be more powerful, efficient, fast. npm's dependency management using npm link does provide the behaviour of re-using the earlier installled depedency but it requires effort to install each package globally first, and that is point less way say if one wants to do re-install all prod-dependencies, one just can't do like
'npm i --link', thats not a option with npm.

Yarn provides more a library solution inspite of a package solution. I mean if something is expected to be re-used its should be exposed by api, not by replicating it separately each time, coz that is a waste of resource(memory).

I know this is a tough choice to suggest i.e., yarn over npm despite fso uses npm in material, but this is totally worth I consider.

What are the downsides though..? 🙂

**Pull request closed without merging**
